#!/bin/bash

read -p "Введите версию плагина (например, 1.2.1): " VERSION

if [ -z "$VERSION" ]; then
  echo "Ошибка: Версия не была введена."
  exit 1
fi

echo "Начинаем процесс... (Займет около 5 минут)"

echo "Сборка проекта..."
./gradlew shadowJar

if [ $? -ne 0 ]; then
  echo "Ошибка: Сборка не удалась."
  exit 1
fi

echo "Создание тега и релиза..."
gh release create $VERSION \
  --title "$VERSION" \
  --notes "Автоматически созданный релиз версии $VERSION"

if [ $? -ne 0 ]; then
  echo "Ошибка: Не удалось создать релиз."
  exit 1
fi

echo "Загрузка JAR-файла в релиз..."
gh release upload $VERSION build/libs/telenukkit-$VERSION.jar

if [ $? -ne 0 ]; then
  echo "Ошибка: Не удалось загрузить JAR-файл в релиз."
  exit 1
fi

echo "Релиз $VERSION успешно создан и JAR-файл загружен!"
