# Config Version - 2.2.1
telegram:
  enabled: true
  botToken: "YOUR_TELEGRAM_BOT_TOKEN"

matrix:
  enabled: true
  homeserver: "https://matrix.example.org"
  accessToken: "YOUR_MATRIX_ACCESS_TOKEN"
  roomId: "!ROOM_ID:matrix.org"
discord:
  enabled: true
  token: "YOUR_TOKEN"
  channel_id: "YOUR_CHANNEL_ID" #NOT WORKED.
  
# languages: en, ru, cn
language: "en"
formats:
  telegram-to-minecraft: "[TG] {sender}: {message}"
  minecraft-to-telegram: "[MC] {sender}: {message}"
  matrix-to-minecraft: "[MX] {sender}: {message}"
  minecraft-to-matrix: "[MC] {sender}: {message}"

settings:
  check-for-updates: true
  first-run-setup: true
