language: en

settings:
  check-for-updates: true
  enable-metrics: true # if you want - disable
  #i need metrics only for knowing what kind Nukkit Fork you use

features:
  cross-chat: true
  join-notifications: true
  quit-notifications: true
  account-linking: true

proxy:
  type: "" # HTTP or SOCKS
  host: ""
  port: 8080
  username: ""
  password: ""

telegram:
  enabled: false
  botToken: "" #get from "@botfather"!

matrix:
  enabled: false
  homeserver: "" #example: matrix.org
  accessToken: "" #check out wiki!
  roomId: ""

discord:
  enabled: false
  token: ""
  channel_id: ""

#customize as you want!
formats:
  telegram-to-minecraft: "[TG] {sender}: {message}"
  matrix-to-minecraft: "[MX] {sender}: {message}"
  discord-to-minecraft: "[DC] {sender}: {message}"
  system-message: "[System] {message}"
  minecraft-to-bridge: "[{sender}] {message}"
