name: TeleNukkit
version: 1.0.1.2b
main: com.debianrose.TeleNukkit.Main
api: ["1.0.0"]
author: debianrose
description: Bridge Between Telegram/Matrix/Discord And Nukkit
commands:
  getlinkcode:
    description: Get a code to link your account
    usage: /getlinkcode
    aliases: [linkcode, codelink, getcodelink]
    permission: telenukkit.user
  unlinkaccount:
    description: Unlink your external account
    usage: /unlinkaccount
    permission: telenukkit.user
  setprefix:
    description: Set your chat prefix
    usage: /setprefix <prefix>
    permission: telenukkit.user
  telesetup:
    description: Configure bridge settings
    usage: /telesetup <telegram|matrix|discord> [settings]
    permission: telenukkit.admin

permissions:
  telenukkit.user:
    description: Basic user permissions
    default: true
  telenukkit.admin:
    description: Admin permissions
    default: op