name: TeleNukkit
version: 1.0.1.2a
main: com.debianrose.TeleNukkit.Main
api: ["1.0.0"]
author: debianrose
description: Bridge Between Telegram/Matrix And Nukkit
commands:
  telesetup:
    description: Configure bridge settings
    usage: /telesetup <telegram|matrix|discord> [settings]
    permission: telenukkit.setup
  setprefix:
    description: Set your chat prefix
    usage: /setprefix <prefix>
  linkaccount:
    description: Link your external account
    usage: /linkaccount <username>
  setlanguage:
    description: Change the plugin language
    usage: /setlanguage <ru|en|es|fr|zh>
    permission: telenukkit.admin

permissions:
  telenukkit.setup:
    description: Allows configuring bridge settings
    default: op
  telenukkit.admin:
    description: Allows admin commands
    default: op
