name: TeleNukkit
version: 1.0.1.4
main: com.debianrose.TeleNukkit.Main
api: ["1.0.0"]
author: debianrose
description: |
  Advanced bridge between Minecraft and messaging platforms
  (Telegram/Matrix/Discord) with account linking

commands:
  telesetup:
    description: Configure bridge connections
    usage: |
      /telesetup telegram <botToken>
      /telesetup matrix <homeserver> <accessToken> <roomId>
      /telesetup discord <token> <channelId>
    permission: telenukkit.admin
  getlinkcode:
    description: Get your account linking code
    usage: /getlinkcode
    aliases: [linkcode, codelink, link]
    permission: telenukkit.user
  unlinkaccount:
    description: Unlink your external account
    usage: /unlinkaccount
    aliases: [unlink]
    permission: telenukkit.user
  togglelinking:
    description: Toggle account linking system
    usage: /togglelinking <on|off>
    permission: telenukkit.admin
  checkupdate:
    description: Check for plugin updates
    usage: /checkupdate
    permission: telenukkit.user
  setlang:
    description: Change plugin language
    usage: /setlang <lang>
    permission: telenukkit.admin
  testproxy:
    description: Test proxy connectivity
    usage: /testproxy
    permission: telenukkit.admin

permissions:
  telenukkit.user:
    description: Allows using basic bridge features
    default: true
  telenukkit.admin:
    description: Allows configuring bridges and system settings
    default: op
