name: Building

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Create Release (only for tags)
      if: startsWith(github.ref, 'refs/tags/')
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (for tags)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: build/libs/tn-1.0.1.2.jar
        asset_name: tn-${{ github.ref_name }}.jar
        asset_content_type: application/java-archive

    - name: Create Draft Release (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      id: create-draft-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: manual-${{ github.run_id }}
        release_name: Manual Release (${{ github.run_id }})
        draft: true
        prerelease: false

    - name: Upload Asset (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-draft-release.outputs.upload_url }}
        asset_path: build/libs/tn-1.0.1.1.jar
        asset_name: tn-manual-${{ github.run_id }}.jar
        asset_content_type: application/java-archive
